name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-tags: true
        fetch-depth: 0

    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=${{ github.workspace }}/extern/cmake-conan/conan_provider.cmake
        -S ${{ github.workspace }}

    - name: Create documentation
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --target CommonUtils_docs

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.strings.outputs.build-output-dir }}/docs/html
